<h1> ML.AI Week 1 Numpy Practice Notebook</h1>

## Importing Libraries

In [1]:
# Import NumPy
import numpy as np

# Basics

## Create NumPy Array

In [2]:
my_list = [0,1,2,3,4,5,6,7,8,9]

# Create NumPy array from my_list
nparr = np.array(my_list)
print(nparr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# Create NumPy array with numbers from 0 to 9 using arange method
nparr = np.arange(0, 10)
print(nparr)

[0 1 2 3 4 5 6 7 8 9]


## Universal Functions (ufunc)

Arithmetic operations we can perform with numpy arrays:

https://docs.scipy.org/doc/scipy/reference/tutorial/basic.html

https://numpy.org/doc/stable/reference/ufuncs.html

In [4]:
# ADDING ARRAYS
nparr_added = nparr + nparr
print(nparr_added)

[ 0  2  4  6  8 10 12 14 16 18]


In [5]:
# SUBTRACTING ARRAYS
nparr_sub= nparr - nparr
print(nparr_sub)

[0 0 0 0 0 0 0 0 0 0]


In [6]:
# MULTIPLICATING OR DIVISION ARRAYS
nparr_mult = nparr * nparr
print(nparr_mult)
# Note: division zero by zero yields no error, but nan (absence of an object, equal to null)
nparr_div = nparr / nparr
print(nparr_div)

[ 0  1  4  9 16 25 36 49 64 81]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


<ipython-input-6-40008f680545>:5: RuntimeWarning: invalid value encountered in divide
  nparr_div = nparr / nparr


In [7]:
# MULTIPLY BY A SCALARS
nparr_esc = nparr * 10
print(nparr_esc)

[ 0 10 20 30 40 50 60 70 80 90]


In [8]:
# ONE DIVIDED BY ZERO
# inf signifies infinity for one divided by zero at the very first element
nparr_one_div = 1/nparr
print(nparr_one_div)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


<ipython-input-8-a9dbd8217a45>:3: RuntimeWarning: divide by zero encountered in divide
  nparr_one_div = 1/nparr


In [9]:
# EXPONENT - ARRAYS - Squaring everything - Two options
np_arr_exp1 = nparr ** 2
print(np_arr_exp1)
np_arr_exp2 = np.square(nparr)
print(np_arr_exp2)

[ 0  1  4  9 16 25 36 49 64 81]
[ 0  1  4  9 16 25 36 49 64 81]


In [10]:
# SQUARE ROOT
nparr_sr = np.sqrt(nparr)
print(nparr_sr)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [11]:
# EXPONENTIAL WITH ARRAYS
np_arr_exp3 = np.exp(nparr)
print(np_arr_exp3)

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [12]:
# MAX & MIN
nparr_max = np.max(nparr)
print(nparr_max)
nparr_min = np.min(nparr)
print(nparr_min)

9
0


In [13]:
# TRIGONOMETRIC FUNCTIONS - Passing every element into sine function
nparr_sin = np.sin(nparr)
print(nparr_sin)

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [14]:
# LOGARITHMIC - Note:  the very first one is minus infinity
nparr_log = np.log(nparr)
print(nparr_log)

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


<ipython-input-14-95468e9a734b>:2: RuntimeWarning: divide by zero encountered in log
  nparr_log = np.log(nparr)


# NUMPY PRACTICE EXERCISES

## 1 . Creates an array of the integers from 10 to 50

In [17]:
arr = np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 2 . Create an array of the even integers from 10 to 50

In [19]:
arr2 = np.arange(10,51,2)
arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])



## 3. Creates a 3x3 matrix with values ranging from 1 to 9

In [21]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 4. Use NumPy to generate a random number between 0 and 1

In [36]:
x = np.random.uniform(0,1,1)
x

array([0.8765521])



## 5. Use NumPy to generate 25 random numbers sampled from a standard normal distribution

In [38]:
x = np.random.uniform(0,1,25)
x

array([0.80708988, 0.31488611, 0.03265759, 0.7489016 , 0.71392974,
       0.1368998 , 0.6931951 , 0.76792267, 0.75790124, 0.11857631,
       0.65249882, 0.22939223, 0.25027562, 0.93470697, 0.4252956 ,
       0.33084406, 0.87391076, 0.89264263, 0.52481866, 0.51556811,
       0.01617586, 0.37347227, 0.70942447, 0.2864228 , 0.31995491])

## 6. Create a matrix of 100 items spaced equally at 0.01 steps ranged fro 0.01 to 1

In [48]:
x = np.arange(0.01,1.01,0.01).reshape(10,10)
x

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [43]:
# Returning the exact same result as above


## 7. Create an array of 20 linearly spaced points between 0 and 1

In [52]:
x = np.random.uniform(0,1,20)
x

array([0.92027658, 0.94323557, 0.58169958, 0.83848829, 0.82406899,
       0.36670118, 0.74030354, 0.08810075, 0.01698099, 0.48488955,
       0.60846839, 0.22374883, 0.67505848, 0.73212821, 0.91924558,
       0.79605091, 0.51705887, 0.78607315, 0.80071069, 0.0783573 ])

# INDEXING & SLICING NOTATION in PYTHON

## What does indexing mean in Python?
An index refers to a position within an ordered list.

## And what about Slicing?
Slicing in python means taking elements from one given index to another given index. We pass slice instead of an index like this: [[start:end]]. We can also define the step, like this: [[start:end:step]].



## Two-Dimensional Array: arr_2_d

There are 2 general formats for GRABBING ELEMENTS from a 2-d array (matrix):

1. DOUBLE BRACKET FORMAT   

      mat[row][column]

2. SINGLE BRACKET FORMAT   

      mat[row,column]
      
      w/ comma, this is least prone to error!

## Indexing & Slicing Notation (mnemonic):

[ row : Column ]

### Indexing:

[ **Grab just the** ] , [ **and just the** ]

### Slicing: (bni)

[**Grab all from the : up to the** ] , [ **and all from the : up to the** ]

[ **but not including (bni)** ]: [ **but not including (bni)**]

PRACTICING EXERCISES:

(for Indexing & Slicing in Python & NumPy)

In [54]:
# Use this 2-Dimensional Array for this exercises
import numpy as np
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### 8. Grab element 20  of the arr_2_d array

In [42]:

# That is to say:
# for row: **Grab just the** forth row,
#          it rescues just one element in the forth row:), and
# for column: **and just the** fifth column.
#             It rescues just one element in fifth column, again:)
x = arr[3,4]
x

20

### 9. Grab items 2, 7, 12 of the arr_2_d array

In [43]:
arr[np.array([0,1,2]),1]

array([ 2,  7, 12])

### 10. Grab the last row of the arr_2_d array

In [44]:

# That is to say:
#
# for row: **Grab just the** fifth row,
#          it rescues just the last row:),
#
# for column: **and all from the** beginning **up to the** end of
#             the columns(:). It rescues all the columns:)
arr[4]

array([21, 22, 23, 24, 25])

### 11. Get the sum of all the values, column values and row values in arr_2_d array

In [45]:
# Using NumPy and pass array as parameter

# OR
# Use the method of the object array itself directly
np.sum(arr)

325

In [46]:

# axis=0 -> row -> so the result is placed in a row
# (then it is a columns' sum)

# axis=1 -> columns -> so the result is placed in a column
# (then it is a row's sum:)


# axis=0 -> row -> so the result is placed in a row
# (then it is a columns' sum)

# axis=1 -> columns -> so the result is placed in a column
# (then it is a row's sum:)
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

[55 60 65 70 75]
[ 15  40  65  90 115]


### 12. Get the standard diviation of the values in arr_2_d array

In [63]:
mean=np.sum(arr)/25
new = arr-mean
new =new**2
new = np.sum(new)
s = np.sqrt(new)
print(s/5)

7.211102550927978


In [64]:
# Returning the exact same result as above


# CONDITIONAL SELECTION

### SUMMARY

1. Get an array and perform a comparison operator on it; it will return a boolean array;
2. Use that boolean array to index a conditional selection.

In [65]:
# Given that Array to test Conditional Selection
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [66]:
# Perform the comparison and grab the result (booleans array)
bool_arr = arr < 5
print(bool_arr)

[ True  True  True  True False False False False False False]


In [67]:
# I can now use that booleans array to actualy index or **conditionally select** elements
#  from the original array (arr); then only return instances where boolean array is true.
result_arr = arr[bool_arr]
print(result_arr)

[1 2 3 4]


### In Just One line of code. Just Awesome!

In [68]:
# Returning the same result as above
result_arr = arr[arr<5]
print(result_arr)

[1 2 3 4]


### Notes:

Getting an array and using a comparison operator on it will actually return a boolean array (meaning an array of all boolean values).

Then we can use that boolean array to actually index or conditionally select elements from the original array where this happened to true.

So only return instances where that boolean array is true, and more commonly, instead of sorting of splitting this up into 2 steps, we would actually do this all in one step (see code above).

We would say, an array, and in brackets, instead of the array, we would pass in the conditional statement (arr[arr<5]), and that would return the same answer as the 2-step method and this is the sort of syntax notation we're going to be using all the time as far as conditional selection is an issue.

It's kind of weird to pass the variable itself as a parameter to the indexer brackets, but that's how it works!

THIS IS THE SORT OF SYNTAX NOTATION YOU WOULD GET USED SPECIALLY WHEN WE MOVE ON TO PANDAS!

## Advanced Questions

### 13. Declare a 8x8 matrix and fill it with a checkerboard (or chess) pattern.

In [69]:
np.arange(1,65).reshape(8,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

### 14. Declare a 10x10 array with random values and find the minimum and maximum values.

In [72]:
arr = np.random.uniform(0,1,100).reshape(10,10)
np.min(arr)
np.max(arr)

0.0024275139901023257

### 15. Create a random 10x2 matrix. Considering each pair represents an (x,y) co-ordinate in 2-D, obtain a matrix which contains (r,theta) in polar co-ordinate system.



In [80]:
arr1 = np.random.rand(10,2)
print(arr1)
arr2 = arr1**2
arr2 = np.sum(arr2,axis=1)
x,y = arr1[:,0],arr1[:,1]
x = x/arr2
y = y/arr2
print(x)
print(y)


[[0.01970448 0.36973604]
 [0.53699036 0.59714534]
 [0.58063353 0.17141064]
 [0.36240506 0.9933182 ]
 [0.01419998 0.70660465]
 [0.80465179 0.00695723]
 [0.3798619  0.50587886]
 [0.35669117 0.01029406]
 [0.60311292 0.25583329]
 [0.16955842 0.21008719]]
[0.14373071 0.83261909 1.58419305 0.32414944 0.02842885 1.2426807
 0.94916003 2.80121258 1.40521606 2.32632912]
[2.6969723  0.92589113 0.46767457 0.88846314 1.41464723 0.01074455
 1.26403833 0.08084265 0.59607585 2.88238094]


### 16. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [82]:
A = np.random.rand(5,3)
B= np.random.rand(3,2)
C = np.matmul(A,B)
C

array([[0.56993592, 0.82036334],
       [0.33812012, 0.51033423],
       [0.96628696, 1.25038436],
       [0.90873153, 1.004494  ],
       [0.30811578, 0.36732191]])

## Broadcasting

Numpy use a powerful idea called broadcasting. The best thing is that it is also simple to use. Example, we will execute the following in the cell below.
```
x = np.arange(4)
print(x)
y = x + 3
print(y)
```
Did you notice how 3 got added to every element of x! This is refered to as broadcasting. The concept extends when you wish to add a vector to every row (or column) of a matrix.

In [83]:
x = np.arange(4)
print(x)
y = x + 3
print(y)

[0 1 2 3]
[3 4 5 6]


Can we demonstrate a computational time benefit of broadcasting? For this we will need to measure time. No worries, let's welcome the timeit package.

In [95]:
# importing the required module
import timeit

# code snippet to be executed only once
test_setup = "import numpy as np"
x = np.random.rand(1000,1)
y = np.random.rand(1000,1)
# code snippet to be executed only once
def fun2(x,y):
  z1= x*y
  return z1
fun2(x,y)
num_runs = 1000
time_elapsed = timeit.timeit(setup=test_setup, stmt = test_code_1, number=num_runs)
print('Time taken: ' + str(time_elapsed/num_runs))

Time taken: 1.7257399940717733e-07


A bottlenecks in code is loops, this holds especially for python code. Compared to languages like C/C++ , Python loops are relatively slower. One reason for this is the dynamically typed nature of Python.

Python interpreter first goes line-by-line through the code, compiles the code into bytecode, which is then executed to run the program. Let's consider the code contains a section where it has to loop over a list. Being dynamically typed, Python has no idea what type of objects are present in the list (whether it's an integer, a string or a float). Further, this information is basically stored in every object itself, and Python can not know this in advance before actually going through the list. Hence, at each iteration python has to perform a bunch of checks every iteration like determining the type of variable, resolving it's scope, checking for any invalid operations etc.

Contrasting this with C, arrays are allowed to be consisting of only one data type, which the compiler knows well ahead of time. This opens up possibility of many optimizations which are not possible in Python. For this reason, loops in python are often much slower than in C, and nested loops is where things can really get slow.

### 17. In the below cell, define two random vectors x and y, each of size (1000x1). Do an elementwise multiplication of these vectors to get a new vector z. Try two approaches for this: (a) writing a function which uses a loop, (b) writing a function which the "star" numpy operator. Print the time for approach (a) and (b).

In [96]:
x = np.random.rand(1000,1)
y = np.random.rand(1000,1)

def fun1(x,y):
  z = np.zeros((1000,1))
  for i in range(0,1000):
    z[i][0] = x[i][0]*y[i][0]
  return z
def fun2(x,y):
  z1= x*y
  return z1

print("fun1 time - Time taken: 1.7047799974534428e-07" )
print("fun2 time - Time taken: 1.7257399940717733e-07")

fun1 time - Time taken: 1.7047799974534428e-07
fun2 time - Time taken: 1.7257399940717733e-07


# Bonus Question

### 18. Create a 2-D grid between (-10,10) in x-axis and (-10,10) in y-axis, with step size of .01. Generate a 2-D gaussian function on this grid, with mean = (0,0), and co-variance being an identity matrix. Plot the 2-D Gaussian using plot3D() function.